export const assets = {
  body: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/default/basic-character.png",
  hair: {
    1: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/hair/hair-1.png",
    2: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/hair/hair-2.png",
    3: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/hair/hair-3.png",
    4: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/hair/hair-4.png",
    5: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/hair/hair-5.png",
    6: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/hair/hair-6.png",
  },
  ear: {
    1: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/ears/ear-1.png",
    2: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/ears/ear-2.png",
    3: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/ears/ear-3.png",
    4: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/ears/ear-4.png",
    5: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/ears/ear-5.png",
  },
  eye: {
    1: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/eyes/eye-1.png",
    2: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/eyes/eye-2.png",
    3: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/eyes/eye-3.png",
    4: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/eyes/eye-4.png",
    5: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/eyes/eye-5.png",
    6: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/eyes/eye-6.png",
  },
  mouth: {
    1: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/mouth/mouth-1.png",
    2: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/mouth/mouth-2.png",
    3: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/mouth/mouth-3.png",
    4: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/mouth/mouth-4.png",
    5: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/mouth/mouth-5.png",
    6: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/mouth/mouth-6.png",
  },
  nose: {
    1: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/nose/nose-1.png",
    2: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/nose/nose-2.png",
    3: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/nose/nose-3.png",
    4: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/nose/nose-4.png",
    5: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/nose/nose-5.png",
    6: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/nose/nose-6.png",
  },
  accessories: {
    1: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/accessories/accessory-1.png",
    2: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/accessories/accessory-2.png",
    3: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/accessories/accessory-3.png",
    4: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/accessories/accessory-4.png",
    5: "https://raw.githubusercontent.com/elise-bigdevsoon/big-dev-soon-character-generator/refs/heads/main/assets/character-images-left-side/accessories/accessory-5.png",
  },
  background: {
    1: "#d2d2d2",
    2: "#565dff",
    3: "#ca56ff",
    4: "#53c336",
    5: "#d6d82a",
    6: "#d98928",
  },
};
